version: 2

sources:
  - name: raw_olist
    database: seikabutu-497407
    schema: raw_olist

    tables:
      - name: orders
      - name: customers
      - name: items
      - name: order_payments
      - name: products
      - name: reviews
      - name: sellers